### ISSUE TITLE
Create inventory of "epics"

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn-analyzers-contrib#10]
These are the major areas of focus for the analyzer ecosystem.

TBD: Are these captured in the wiki, as a set of issues, something else?

**Comment by sharwell** [comment]
I would prefer to disable the wiki, as described in dotnet/corefx#1781. Generally the focus areas would appear as labels that can be applied to issues.

**Comment by ghost** [comment]
@sharwell A docs directory makes sense. And I agree that each of the focus areas should correspond to a label.

It's still worth creating the "inventory" document, IMO, so that the community has a common understanding of what each of the areas means. There's more background than can be conveyed by a label. What do you think?

**Comment by srivatsn** [comment]
Disabled the wiki.

**Comment by ghost** [comment]
Thanks @srivatsn
